@startuml

[*] --> GreenLed : esp_rom_gpio_pad_select_gpio(pinButton);, gpio_reset_pin((gpio_num_t)pinButton);, gpio_set_direction((gpio_num_t)pinButton, GPIO_MODE_INPUT);

GreenLed : entry/ gpio_set_level((gpio_num_t)pinGLED,0);, blinks = 0
OrangeLed : entry/  gpio_set_level((gpio_num_t)pinRLED,0);
RedLed :  entry/ gpio_set_level((gpio_num_t)pinGLED,1);
RedBlink : entry/ gpio_set_level((gpio_num_t)pinGLED,1);
OrangeBlink: entry/ gpio_set_level((gpio_num_t)pinGLED,0);, blinks++

state c1 <<choice>>
state c2 <<choice>>
state c3 <<choice>>

GreenLed --> c1 : after(100ms)
c1 --> OrangeLed : [btnKlikA.isPressed()]
c1 ---> GreenLed : after(100ms)[else]
OrangeLed --> RedLed : after(3s)
c2 ---> OrangeBlink : [btnKlikB.isPressed()]
RedBlink --> OrangeBlink : after(500ms)
OrangeBlink --> c3 : after(100ms)
RedLed --> c2 : after (100ms)
c2 --> RedLed : after(100ms)[else]
c3 --> GreenLed : after(500ms)[blinks == 5]
c3 --> RedBlink : after(500ms)[else]

@enduml

' Het verkeerslicht zal normaal op groen staan. Het heeft drie kleuren: groen – oranje/geel – rood. 
' - 	Knopje A is verbonden met de knop van het voetgangerspad op de straat die er loodrecht op staat/loopt.
' - 	Knopje B is verbonden met de knop van het voetgangerspad van de straat waar het stoplicht staat.
' - 	Het verkeerslicht staat normaal op groen. Als op knopje A wordt gedrukt moet het verkeerslicht van groen -> oranje/geel (3 seconden) -> rood gaan. Dan moet hij op rood blijven staan.
' - 	Als knopje B wordt ingedrukt moet hij (het is een duits verkeerslicht) van rood -> knipperend rood/geel gaan. Dus 5 x (oranje/geel (0.5 s) -> rood (0.5 s) -> en weer terug naar oranje).
' - 	Uiteindelijk na die 5 keer knipperen moet hij naar groen gaan. 