@startuml

[*] --> GreenLed : esp_rom_gpio_pad_select_gpio(pinButton);, gpio_reset_pin((gpio_num_t)pinButton);, gpio_set_direction((gpio_num_t)pinButton, GPIO_MODE_INPUT);

GreenLed : entry/ greenLed.setDuty(60);, redLed.setDuty(0); , blinks = 0
OrangeLed : entry/  greenLed.setDuty(6);, redLed.setDuty(100);
RedLed :  entry/ redLed.setDuty(100);
RedBlink : entry/ greenLed.setDuty(0);, redLed.setDuty(100);
OrangeBlink: entry/ greenLed.setDuty(6);, blinks++

state c1 <<choice>>
state c2 <<choice>>
state c3 <<choice>>

GreenLed --> c1
c1 --> OrangeLed : wait(flagKnopIngedruktA)[flagKnopIngedruktA]
c1 ---> GreenLed : wait(flagKnopIngedruktA)[else]
OrangeLed --> RedLed : after(3s)
c2 ---> OrangeBlink : wait(flagKnopIngedruktB)[flagKnopIngedruktB]
OrangeBlink --> RedBlink : after(500ms)
c3 -->  OrangeBlink : after(500ms)
RedLed --> c2
c2 --> RedLed : wait(flagKnopIngedruktB)[else]
c3 --> GreenLed : after(500ms)[blinks == 5]
RedBlink --> c3

@enduml

' Het verkeerslicht zal normaal op groen staan. Het heeft drie kleuren: groen – oranje/geel – rood. 
' - 	Knopje A is verbonden met de knop van het voetgangerspad op de straat die er loodrecht op staat/loopt.
' - 	Knopje B is verbonden met de knop van het voetgangerspad van de straat waar het stoplicht staat.
' - 	Het verkeerslicht staat normaal op groen. Als op knopje A wordt gedrukt moet het verkeerslicht van groen -> oranje/geel (3 seconden) -> rood gaan. Dan moet hij op rood blijven staan.
' - 	Als knopje B wordt ingedrukt moet hij (het is een duits verkeerslicht) van rood -> knipperend rood/geel gaan. Dus 5 x (oranje/geel (0.5 s) -> rood (0.5 s) -> en weer terug naar oranje).
' - 	Uiteindelijk na die 5 keer knipperen moet hij naar groen gaan. 